---

# see: https://github.com/marketplace/actions/upload-files-to-a-github-release

name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binary
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build dependencies
      run: sudo apt-get install -y libssl-dev liblzo2-dev libpam0g-dev build-essential

    - name: Build with --enable-iproute2
      run: bash build.sh "${{ github.ref_name }}" "--enable-iproute2"

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/openvpn
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: 'OpenVPN Debian-based'
