---

# see: https://github.com/marketplace/actions/upload-files-to-a-github-release

name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binary
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build dependencies
      run: sudo apt-get install -y libssl-dev liblzo2-dev libpam0g-dev libcap-ng-dev liblz4-dev build-essential

    - name: Build with --enable-iproute2
      run: bash build.sh "${{ github.ref_name }}" "--enable-iproute2"

    - name: Upload ubuntu binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        file: "/tmp/openvpn_${{ github.ref_name }}"
        asset_name: 'openvpn-ubuntu+enable-iproute2'
        tag: "${{ github.ref }}"
        overwrite: true

    - name: Upload debian binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        file: "/tmp/openvpn_${{ github.ref_name }}"
        asset_name: 'openvpn-debian+enable-iproute2'
        tag: "${{ github.ref }}"
        overwrite: true
