---

name: Check for new releases

on:
  schedule:
    - cron: '42 21 * * *'

jobs:
  check:
    name: Checking for new OpenVPN releases
    runs-on: ubuntu-latest
    outputs:
      releases: "${{ steps.check_job.outputs.json }}"

    steps:
    - uses: actions/checkout@v3

    - name: Check for new releases
      run: |
        releases=$(python3 scripts/get_new_releases.py)
        echo "RELEASES: '${releases}'"
        echo "json=${releases}" >> $GITHUB_OUTPUT
      shell: bash
      id: check_job

  release:
    name: Creating missing releases
    needs: [check]
    if: "${{ needs.check.outputs.releases != '[]' }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: "${{ fromJson(needs.check.outputs.releases) }}"

    steps:
      - name: "Create Release ${{ matrix.value }}"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_KEY }}"
        with:
          tag_name: "${{ matrix.value }}"
          release_name: "${{ matrix.value }}"
          draft: false
          prerelease: false
          body: "Re-compiled OpenVPN binaries of <a href=https://github.com/OpenVPN/openvpn/releases/tag/v${{ matrix.value }}>version ${{ matrix.value }}</a>"
